name: Build and Release Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Backend Docker Image
        run: |
          docker build -t backend:latest ./backend
          docker save backend:latest | gzip > backend-image.tar.gz

      - name: Upload Backend Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-image
          path: backend-image.tar.gz

  build-frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Frontend Docker Image
        run: |
          docker build -t frontend:latest ./frontend
          docker save frontend:latest | gzip > frontend-image.tar.gz

      - name: Upload Frontend Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-image
          path: frontend-image.tar.gz

  create-release:
    name: Create GitHub Release
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Download Backend Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-image

      - name: Download Frontend Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-image

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Backend Image to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: backend-image.tar.gz
          asset_name: backend-image.tar.gz
          asset_content_type: application/gzip

      - name: Upload Frontend Image to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: frontend-image.tar.gz
          asset_name: frontend-image.tar.gz
          asset_content_type: application/gzip